import type {
  ClasificacionEntry,
  EquipoManager,
  JugadorLiga,
  MercadoListing,
  PlantillaSlot,
} from "./types";

// Datos ficticios solo para desarrollar la interfaz mientras no hay
// conexión real a Supabase. Sustituir por llamadas a la base de datos
// (ver lib/supabase/client.ts) en cuanto exista el esquema.

export const mockEquipo: EquipoManager = {
  id: "mock-equipo",
  leagueId: "mock-liga",
  nombreEquipo: "Ostadar taldea",
  saldo: 18,
};

export const mockPlantilla: PlantillaSlot[] = [
  {
    jugador: {
      id: "1",
      nombre: "Asier Corral",
      club: "Berain Bera B",
      categoria: 1,
      elo: 2050,
      valorMercado: 32,
      activo: true,
    },
    puntosJornada: 7,
    valorMercadoDelta: 2,
    resultadosRecientes: ["victoria", "victoria", "victoria"],
    historialPuntos: [
      { jornada: 1, puntos: 4 },
      { jornada: 2, puntos: 7 },
      { jornada: 3, puntos: 0 },
      { jornada: 4, puntos: 5 },
      { jornada: 5, puntos: 9 },
      { jornada: 6, puntos: 3 },
      { jornada: 7, puntos: 7 },
    ],
  },
  {
    jugador: {
      id: "2",
      nombre: "Ekaitz Mendizabal Guridi",
      club: "Arrasate-Arlutz C",
      categoria: 1,
      elo: 1985,
      valorMercado: 28,
      activo: true,
    },
    puntosJornada: 4,
    valorMercadoDelta: 1,
    resultadosRecientes: ["victoria", "victoria", "victoria", "tablas"],
    historialPuntos: [
      { jornada: 1, puntos: 3 },
      { jornada: 2, puntos: 5 },
      { jornada: 3, puntos: 5 },
      { jornada: 4, puntos: 0 },
      { jornada: 5, puntos: 7 },
      { jornada: 6, puntos: 4 },
      { jornada: 7, puntos: 3 },
    ],
  },
];

export const mockMercado: MercadoListing[] = [
  {
    jugador: {
      id: "10",
      nombre: "Peio Urrutia",
      club: "Arrasate-Arlutz B",
      categoria: 1,
      elo: 2210,
      valorMercado: 47,
      activo: true,
    },
    rival: { nombre: "Nagore Etxarri", elo: 1990 },
    numeroPujas: 6,
    historialPuntos: [
      { jornada: 1, puntos: 7 },
      { jornada: 2, puntos: 9 },
      { jornada: 3, puntos: 5 },
      { jornada: 4, puntos: 7 },
      { jornada: 5, puntos: 9 },
      { jornada: 6, puntos: 5 },
      { jornada: 7, puntos: 9 },
    ],
  },
];

export const mockClasificacion: ClasificacionEntry[] = [
  {
    posicion: 1,
    nombreEquipo: "Haizea BT",
    puntos: 268,
    historialPuntos: [
      { jornada: 1, puntos: 35 },
      { jornada: 2, puntos: 40 },
      { jornada: 3, puntos: 38 },
      { jornada: 4, puntos: 42 },
      { jornada: 5, puntos: 36 },
      { jornada: 6, puntos: 39 },
      { jornada: 7, puntos: 38 },
    ],
  },
  {
    posicion: 2,
    nombreEquipo: "Zurriola FC",
    puntos: 249,
    historialPuntos: [
      { jornada: 1, puntos: 34 },
      { jornada: 2, puntos: 36 },
      { jornada: 3, puntos: 33 },
      { jornada: 4, puntos: 37 },
      { jornada: 5, puntos: 35 },
      { jornada: 6, puntos: 38 },
      { jornada: 7, puntos: 36 },
    ],
  },
  {
    posicion: 3,
    nombreEquipo: "Ostadar taldea",
    puntos: 231,
    esMiEquipo: true,
    historialPuntos: [
      { jornada: 1, puntos: 30 },
      { jornada: 2, puntos: 33 },
      { jornada: 3, puntos: 31 },
      { jornada: 4, puntos: 35 },
      { jornada: 5, puntos: 29 },
      { jornada: 6, puntos: 36 },
      { jornada: 7, puntos: 37 },
    ],
  },
  {
    posicion: 4,
    nombreEquipo: "Amaraberri",
    puntos: 219,
    historialPuntos: [
      { jornada: 1, puntos: 28 },
      { jornada: 2, puntos: 30 },
      { jornada: 3, puntos: 29 },
      { jornada: 4, puntos: 32 },
      { jornada: 5, puntos: 31 },
      { jornada: 6, puntos: 33 },
      { jornada: 7, puntos: 36 },
    ],
  },
  {
    posicion: 5,
    nombreEquipo: "Kresala AE",
    puntos: 204,
    historialPuntos: [
      { jornada: 1, puntos: 26 },
      { jornada: 2, puntos: 28 },
      { jornada: 3, puntos: 27 },
      { jornada: 4, puntos: 30 },
      { jornada: 5, puntos: 29 },
      { jornada: 6, puntos: 32 },
      { jornada: 7, puntos: 32 },
    ],
  },
];

// Todos los jugadores de la liga, incluidos los de los equipos rivales
// (para el desplegable de Clasificación) y los libres (para Jugadores/
// Mercado). Un único listado, para que ofertas y clausulazos —que viven
// en GameStateProvider— funcionen sobre los mismos jugadores se mire
// desde donde se mire, en vez de tener datos de plantillas rivales
// sueltos por otro lado. Jugadores sacados del listado real de la liga
// (categorías Primera, Segunda y Tercera — Preferente no entra en el
// Fantasy).
export const mockJugadoresLiga: JugadorLiga[] = [
  {
    id: "1",
    nombre: "Asier Corral",
    club: "Berain Bera B",
    categoria: 1,
    elo: 2050,
    valorMercado: 32,
    activo: true,
    puntosTotales: 156,
    propietario: "Ostadar taldea",
    esMiEquipo: true,
    historialPuntos: [
      { jornada: 1, puntos: 4 },
      { jornada: 2, puntos: 7 },
      { jornada: 3, puntos: 0 },
      { jornada: 4, puntos: 5 },
      { jornada: 5, puntos: 9 },
      { jornada: 6, puntos: 3 },
      { jornada: 7, puntos: 7 },
    ],
  },
  {
    id: "2",
    nombre: "Ekaitz Mendizabal Guridi",
    club: "Arrasate-Arlutz C",
    categoria: 1,
    elo: 1985,
    valorMercado: 28,
    activo: true,
    puntosTotales: 141,
    propietario: "Ostadar taldea",
    esMiEquipo: true,
    historialPuntos: [
      { jornada: 1, puntos: 3 },
      { jornada: 2, puntos: 5 },
      { jornada: 3, puntos: 5 },
      { jornada: 4, puntos: 0 },
      { jornada: 5, puntos: 7 },
      { jornada: 6, puntos: 4 },
      { jornada: 7, puntos: 3 },
    ],
  },
  {
    id: "10",
    nombre: "Peio Urrutia",
    club: "Arrasate-Arlutz B",
    categoria: 1,
    elo: 2210,
    valorMercado: 47,
    activo: true,
    puntosTotales: 198,
    propietario: null,
    historialPuntos: [
      { jornada: 1, puntos: 7 },
      { jornada: 2, puntos: 9 },
      { jornada: 3, puntos: 5 },
      { jornada: 4, puntos: 7 },
      { jornada: 5, puntos: 9 },
      { jornada: 6, puntos: 5 },
      { jornada: 7, puntos: 9 },
    ],
  },
  {
    id: "11",
    nombre: "Xabier Garmendia Díaz",
    club: "Santikutz A",
    categoria: 1,
    elo: 1990,
    valorMercado: 33,
    activo: true,
    puntosTotales: 133,
    propietario: "Haizea BT",
    historialPuntos: [
      { jornada: 1, puntos: 3 },
      { jornada: 2, puntos: 4 },
      { jornada: 3, puntos: 5 },
      { jornada: 4, puntos: 0 },
      { jornada: 5, puntos: 5 },
      { jornada: 6, puntos: 3 },
      { jornada: 7, puntos: 5 },
    ],
  },
  {
    id: "12",
    nombre: "Agustin Mazkiaran Navarro",
    club: "Agustin de Leiza B",
    categoria: 2,
    elo: 1870,
    valorMercado: 21,
    activo: true,
    puntosTotales: 98,
    propietario: "Zurriola FC",
    historialPuntos: [
      { jornada: 1, puntos: 2 },
      { jornada: 2, puntos: 3 },
      { jornada: 3, puntos: 0 },
      { jornada: 4, puntos: 5 },
      { jornada: 5, puntos: 0 },
      { jornada: 6, puntos: 4 },
      { jornada: 7, puntos: 0 },
    ],
  },
  {
    id: "13",
    nombre: "Illart Alcorta Andoaga",
    club: "Agustin de Leiza C",
    categoria: 3,
    elo: 1640,
    valorMercado: 14,
    activo: true,
    puntosTotales: 62,
    propietario: null,
    historialPuntos: [
      { jornada: 1, puntos: 0 },
      { jornada: 2, puntos: 3 },
      { jornada: 3, puntos: 5 },
      { jornada: 4, puntos: 0 },
      { jornada: 5, puntos: 3 },
      { jornada: 6, puntos: 4 },
      { jornada: 7, puntos: 5 },
    ],
  },
  {
    id: "21",
    nombre: "Josu Astigarraga Toledo",
    club: "Alfil B",
    categoria: 1,
    elo: 2005,
    valorMercado: 30,
    activo: true,
    puntosTotales: 128,
    propietario: "Haizea BT",
    historialPuntos: [
      { jornada: 1, puntos: 5 },
      { jornada: 2, puntos: 3 },
      { jornada: 3, puntos: 7 },
      { jornada: 4, puntos: 0 },
      { jornada: 5, puntos: 5 },
      { jornada: 6, puntos: 4 },
      { jornada: 7, puntos: 4 },
    ],
  },
  {
    id: "22",
    nombre: "Fernando Puga Senar",
    club: "Luzaro Orereta",
    categoria: 1,
    elo: 1970,
    valorMercado: 27,
    activo: true,
    puntosTotales: 119,
    propietario: "Haizea BT",
    historialPuntos: [
      { jornada: 1, puntos: 4 },
      { jornada: 2, puntos: 4 },
      { jornada: 3, puntos: 3 },
      { jornada: 4, puntos: 5 },
      { jornada: 5, puntos: 0 },
      { jornada: 6, puntos: 5 },
      { jornada: 7, puntos: 3 },
    ],
  },
  {
    id: "23",
    nombre: "Jose Luis Godoy Magdaleno",
    club: "Agustin de Leiza B",
    categoria: 2,
    elo: 1830,
    valorMercado: 19,
    activo: true,
    puntosTotales: 87,
    propietario: "Haizea BT",
    historialPuntos: [
      { jornada: 1, puntos: 0 },
      { jornada: 2, puntos: 3 },
      { jornada: 3, puntos: 4 },
      { jornada: 4, puntos: 5 },
      { jornada: 5, puntos: 0 },
      { jornada: 6, puntos: 3 },
      { jornada: 7, puntos: 4 },
    ],
  },
  {
    id: "24",
    nombre: "Juan Miguel Imaz Iribarren",
    club: "Agustin de Leiza C",
    categoria: 3,
    elo: 1660,
    valorMercado: 15,
    activo: true,
    puntosTotales: 58,
    propietario: "Haizea BT",
    historialPuntos: [
      { jornada: 1, puntos: 3 },
      { jornada: 2, puntos: 0 },
      { jornada: 3, puntos: 5 },
      { jornada: 4, puntos: 3 },
      { jornada: 5, puntos: 0 },
      { jornada: 6, puntos: 4 },
      { jornada: 7, puntos: 0 },
    ],
  },
  {
    id: "25",
    nombre: "Aitor Beorlegui Gonzalez",
    club: "Eibar B",
    categoria: 3,
    elo: 1615,
    valorMercado: 13,
    activo: true,
    puntosTotales: 51,
    propietario: "Haizea BT",
    historialPuntos: [
      { jornada: 1, puntos: 0 },
      { jornada: 2, puntos: 4 },
      { jornada: 3, puntos: 3 },
      { jornada: 4, puntos: 0 },
      { jornada: 5, puntos: 5 },
      { jornada: 6, puntos: 3 },
      { jornada: 7, puntos: 0 },
    ],
  },
  {
    id: "26",
    nombre: "Asier Lasa Garmendia",
    club: "Arrasate-Arlutz B",
    categoria: 1,
    elo: 2020,
    valorMercado: 29,
    activo: true,
    puntosTotales: 122,
    propietario: "Zurriola FC",
    historialPuntos: [
      { jornada: 1, puntos: 5 },
      { jornada: 2, puntos: 5 },
      { jornada: 3, puntos: 0 },
      { jornada: 4, puntos: 4 },
      { jornada: 5, puntos: 7 },
      { jornada: 6, puntos: 3 },
      { jornada: 7, puntos: 4 },
    ],
  },
  {
    id: "27",
    nombre: "Jose Ignacio Etxeberria",
    club: "Taula A",
    categoria: 1,
    elo: 1995,
    valorMercado: 26,
    activo: true,
    puntosTotales: 114,
    propietario: "Zurriola FC",
    historialPuntos: [
      { jornada: 1, puntos: 3 },
      { jornada: 2, puntos: 4 },
      { jornada: 3, puntos: 5 },
      { jornada: 4, puntos: 3 },
      { jornada: 5, puntos: 0 },
      { jornada: 6, puntos: 5 },
      { jornada: 7, puntos: 4 },
    ],
  },
  {
    id: "28",
    nombre: "Miguel Ángel Muela Pérez",
    club: "Bergara A",
    categoria: 2,
    elo: 1810,
    valorMercado: 18,
    activo: true,
    puntosTotales: 82,
    propietario: "Zurriola FC",
    historialPuntos: [
      { jornada: 1, puntos: 0 },
      { jornada: 2, puntos: 3 },
      { jornada: 3, puntos: 3 },
      { jornada: 4, puntos: 4 },
      { jornada: 5, puntos: 0 },
      { jornada: 6, puntos: 4 },
      { jornada: 7, puntos: 3 },
    ],
  },
  {
    id: "29",
    nombre: "Santiago Almandoz Zapiain",
    club: "Astigarraga C",
    categoria: 3,
    elo: 1605,
    valorMercado: 12,
    activo: true,
    puntosTotales: 49,
    propietario: "Zurriola FC",
    historialPuntos: [
      { jornada: 1, puntos: 0 },
      { jornada: 2, puntos: 3 },
      { jornada: 3, puntos: 0 },
      { jornada: 4, puntos: 4 },
      { jornada: 5, puntos: 3 },
      { jornada: 6, puntos: 0 },
      { jornada: 7, puntos: 5 },
    ],
  },
  {
    id: "30",
    nombre: "Peio Etxebeste Garitano",
    club: "Agustin de Leiza C",
    categoria: 3,
    elo: 1598,
    valorMercado: 11,
    activo: true,
    puntosTotales: 45,
    propietario: "Zurriola FC",
    historialPuntos: [
      { jornada: 1, puntos: 3 },
      { jornada: 2, puntos: 0 },
      { jornada: 3, puntos: 4 },
      { jornada: 4, puntos: 0 },
      { jornada: 5, puntos: 3 },
      { jornada: 6, puntos: 0 },
      { jornada: 7, puntos: 5 },
    ],
  },
  {
    id: "31",
    nombre: "German Herrera Ortega",
    club: "Alfil B",
    categoria: 1,
    elo: 1960,
    valorMercado: 25,
    activo: true,
    puntosTotales: 108,
    propietario: "Amaraberri",
    historialPuntos: [
      { jornada: 1, puntos: 3 },
      { jornada: 2, puntos: 5 },
      { jornada: 3, puntos: 0 },
      { jornada: 4, puntos: 4 },
      { jornada: 5, puntos: 3 },
      { jornada: 6, puntos: 5 },
      { jornada: 7, puntos: 3 },
    ],
  },
  {
    id: "32",
    nombre: "Harri Lasa Bengoa",
    club: "Arrasate-Arlutz B",
    categoria: 1,
    elo: 1940,
    valorMercado: 24,
    activo: true,
    puntosTotales: 101,
    propietario: "Amaraberri",
    historialPuntos: [
      { jornada: 1, puntos: 4 },
      { jornada: 2, puntos: 0 },
      { jornada: 3, puntos: 5 },
      { jornada: 4, puntos: 3 },
      { jornada: 5, puntos: 4 },
      { jornada: 6, puntos: 0 },
      { jornada: 7, puntos: 5 },
    ],
  },
  {
    id: "33",
    nombre: "Joseba Urdangarín Lasa",
    club: "Santikutz B",
    categoria: 2,
    elo: 1795,
    valorMercado: 17,
    activo: true,
    puntosTotales: 73,
    propietario: "Amaraberri",
    historialPuntos: [
      { jornada: 1, puntos: 0 },
      { jornada: 2, puntos: 3 },
      { jornada: 3, puntos: 4 },
      { jornada: 4, puntos: 0 },
      { jornada: 5, puntos: 3 },
      { jornada: 6, puntos: 4 },
      { jornada: 7, puntos: 0 },
    ],
  },
  {
    id: "34",
    nombre: "Juan Cruz Figueras",
    club: "Taula B",
    categoria: 2,
    elo: 1780,
    valorMercado: 16,
    activo: true,
    puntosTotales: 69,
    propietario: "Amaraberri",
    historialPuntos: [
      { jornada: 1, puntos: 3 },
      { jornada: 2, puntos: 0 },
      { jornada: 3, puntos: 3 },
      { jornada: 4, puntos: 4 },
      { jornada: 5, puntos: 0 },
      { jornada: 6, puntos: 3 },
      { jornada: 7, puntos: 4 },
    ],
  },
  {
    id: "35",
    nombre: "David Losada Cabrera",
    club: "Agustin de Leiza C",
    categoria: 3,
    elo: 1590,
    valorMercado: 11,
    activo: true,
    puntosTotales: 44,
    propietario: "Amaraberri",
    historialPuntos: [
      { jornada: 1, puntos: 0 },
      { jornada: 2, puntos: 3 },
      { jornada: 3, puntos: 0 },
      { jornada: 4, puntos: 4 },
      { jornada: 5, puntos: 0 },
      { jornada: 6, puntos: 3 },
      { jornada: 7, puntos: 4 },
    ],
  },
  {
    id: "36",
    nombre: "Diogo Vale Faria",
    club: "Eibar B",
    categoria: 3,
    elo: 1580,
    valorMercado: 10,
    activo: true,
    puntosTotales: 40,
    propietario: "Amaraberri",
    historialPuntos: [
      { jornada: 1, puntos: 3 },
      { jornada: 2, puntos: 0 },
      { jornada: 3, puntos: 3 },
      { jornada: 4, puntos: 0 },
      { jornada: 5, puntos: 4 },
      { jornada: 6, puntos: 0 },
      { jornada: 7, puntos: 3 },
    ],
  },
  {
    id: "37",
    nombre: "Jokin Fernandez Zubitur",
    club: "Alfil B",
    categoria: 1,
    elo: 1925,
    valorMercado: 23,
    activo: true,
    puntosTotales: 96,
    propietario: "Kresala AE",
    historialPuntos: [
      { jornada: 1, puntos: 3 },
      { jornada: 2, puntos: 4 },
      { jornada: 3, puntos: 0 },
      { jornada: 4, puntos: 5 },
      { jornada: 5, puntos: 0 },
      { jornada: 6, puntos: 4 },
      { jornada: 7, puntos: 3 },
    ],
  },
  {
    id: "38",
    nombre: "Urtzi Lasa Bengoa",
    club: "Arrasate-Arlutz B",
    categoria: 1,
    elo: 1910,
    valorMercado: 22,
    activo: true,
    puntosTotales: 90,
    propietario: "Kresala AE",
    historialPuntos: [
      { jornada: 1, puntos: 4 },
      { jornada: 2, puntos: 0 },
      { jornada: 3, puntos: 3 },
      { jornada: 4, puntos: 4 },
      { jornada: 5, puntos: 3 },
      { jornada: 6, puntos: 0 },
      { jornada: 7, puntos: 4 },
    ],
  },
  {
    id: "39",
    nombre: "Claudio Mendikute Fierro",
    club: "Agustin de Leiza B",
    categoria: 2,
    elo: 1765,
    valorMercado: 15,
    activo: true,
    puntosTotales: 65,
    propietario: "Kresala AE",
    historialPuntos: [
      { jornada: 1, puntos: 0 },
      { jornada: 2, puntos: 3 },
      { jornada: 3, puntos: 0 },
      { jornada: 4, puntos: 4 },
      { jornada: 5, puntos: 3 },
      { jornada: 6, puntos: 0 },
      { jornada: 7, puntos: 4 },
    ],
  },
  {
    id: "40",
    nombre: "Ismael Antón Reparaz",
    club: "Santikutz B",
    categoria: 2,
    elo: 1750,
    valorMercado: 14,
    activo: true,
    puntosTotales: 61,
    propietario: "Kresala AE",
    historialPuntos: [
      { jornada: 1, puntos: 3 },
      { jornada: 2, puntos: 0 },
      { jornada: 3, puntos: 4 },
      { jornada: 4, puntos: 0 },
      { jornada: 5, puntos: 3 },
      { jornada: 6, puntos: 3 },
      { jornada: 7, puntos: 0 },
    ],
  },
  {
    id: "41",
    nombre: "Rubén Sebastiani Paoli",
    club: "Agustin de Leiza C",
    categoria: 3,
    elo: 1570,
    valorMercado: 10,
    activo: true,
    puntosTotales: 38,
    propietario: "Kresala AE",
    historialPuntos: [
      { jornada: 1, puntos: 0 },
      { jornada: 2, puntos: 3 },
      { jornada: 3, puntos: 0 },
      { jornada: 4, puntos: 3 },
      { jornada: 5, puntos: 0 },
      { jornada: 6, puntos: 4 },
      { jornada: 7, puntos: 0 },
    ],
  },
  {
    id: "42",
    nombre: "Iker Garcia Escribano",
    club: "Eibar B",
    categoria: 3,
    elo: 1560,
    valorMercado: 9,
    activo: true,
    puntosTotales: 34,
    propietario: "Kresala AE",
    historialPuntos: [
      { jornada: 1, puntos: 3 },
      { jornada: 2, puntos: 0 },
      { jornada: 3, puntos: 3 },
      { jornada: 4, puntos: 0 },
      { jornada: 5, puntos: 0 },
      { jornada: 6, puntos: 4 },
      { jornada: 7, puntos: 0 },
    ],
  },
];